"""
Evidence schema - represents immutable evidence records from agent decisions.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional
from enum import Enum
from pydantic import BaseModel, Field


class EvidenceType(str, Enum):
    """Types of evidence generated by agents."""
    DOCUMENT_EXTRACTION = "DOCUMENT_EXTRACTION"
    INCOME_VERIFICATION = "INCOME_VERIFICATION"
    CREDIT_CHECK = "CREDIT_CHECK"
    FRAUD_ASSESSMENT = "FRAUD_ASSESSMENT"
    COMPLIANCE_CHECK = "COMPLIANCE_CHECK"
    RISK_CALCULATION = "RISK_CALCULATION"
    APPROVAL_DECISION = "APPROVAL_DECISION"


class VerificationStatus(str, Enum):
    """Verification status."""
    MATCH = "MATCH"
    MISMATCH = "MISMATCH"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    PENDING = "PENDING"
    ERROR = "ERROR"


class EvidenceItem(BaseModel):
    """Single piece of evidence from an agent."""
    evidence_id: str = Field(default_factory=lambda: __import__('uuid').uuid4().hex, description="Unique evidence ID")
    agent_name: str = Field(..., description="Name of agent that produced evidence")
    agent_version: str = Field(..., description="Version of agent")
    evidence_type: EvidenceType = Field(..., description="Type of evidence")
    
    # Evidence content
    description: str = Field(..., description="Human-readable description")
    key_findings: Dict[str, Any] = Field(default_factory=dict, description="Key findings")
    supporting_data: Optional[Dict[str, Any]] = Field(default=None, description="Raw supporting data")
    
    # Confidence and source
    confidence: float = Field(ge=0, le=1, description="Confidence score (0-1)")
    source_refs: List[str] = Field(default_factory=list, description="Source references")
    
    # Metadata
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Creation timestamp")
    reasoning: Optional[str] = Field(default=None, description="Agent reasoning")


class IncomeVerificationEvidence(EvidenceItem):
    """Income verification evidence."""
    verification_status: VerificationStatus
    stated_income: float
    verified_income: float
    variance_percentage: float
    discrepancies: List[str] = Field(default_factory=list)


class CreditScoringEvidence(EvidenceItem):
    """Credit scoring evidence."""
    credit_score: int
    risk_level: str
    credit_history_months: int
    payment_history: str
    credit_utilization: float


class FraudDetectionEvidence(EvidenceItem):
    """Fraud detection evidence."""
    fraud_risk_score: float
    fraud_flags: List[str] = Field(default_factory=list)
    blacklist_match: bool
    device_anomaly: bool
    identity_verification_result: str


class ComplianceCheckEvidence(EvidenceItem):
    """Compliance check evidence."""
    sanction_check_passed: bool
    aml_check_passed: bool
    policy_violations: List[str] = Field(default_factory=list)
    regulatory_notes: Optional[str] = None


class RiskAssessmentEvidence(EvidenceItem):
    """Risk assessment evidence."""
    overall_risk_level: str  # LOW, MEDIUM, MEDIUM_HIGH, HIGH
    risk_factors: Dict[str, float] = Field(description="Risk factor scores")
    risk_summary: str = Field(description="Summary of risk assessment")


class EvidenceLog(BaseModel):
    """Immutable log of all evidence from an application."""
    application_id: str = Field(..., description="Associated application")
    workflow_id: str = Field(..., description="Associated workflow")
    evidence_items: List[EvidenceItem] = Field(default_factory=list, description="All evidence items")
    
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    
    def add_evidence(self, evidence: EvidenceItem) -> None:
        """Add evidence item to immutable log."""
        self.evidence_items.append(evidence)
        self.updated_at = datetime.utcnow()
    
    def get_evidence_by_type(self, evidence_type: EvidenceType) -> List[EvidenceItem]:
        """Retrieve evidence by type."""
        return [e for e in self.evidence_items if e.evidence_type == evidence_type]
    
    def get_evidence_by_agent(self, agent_name: str) -> List[EvidenceItem]:
        """Retrieve evidence by agent name."""
        return [e for e in self.evidence_items if e.agent_name == agent_name]
